-- 数据表空间
CREATE TABLESPACE PSPM DATAFILE 
  'C:\oracle\oradata\orcl\PSPM.DBF' SIZE 30M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;
--drop user PSPM cascade;
CREATE USER "PSPM"  PROFILE "DEFAULT" 
    IDENTIFIED BY "PSPM" DEFAULT TABLESPACE "PSPM" 
    QUOTA UNLIMITED 
    ON "PSPM" 
    ACCOUNT UNLOCK;
GRANT CREATE ANY SYNONYM TO "PSPM";
GRANT CREATE ANY INDEX TO "PSPM";
GRANT CREATE PROCEDURE TO "PSPM";
GRANT CREATE SEQUENCE TO "PSPM";
GRANT CREATE TABLE TO "PSPM";
GRANT CREATE TRIGGER TO "PSPM";
GRANT CREATE VIEW TO "PSPM";
GRANT SELECT ANY SEQUENCE TO "PSPM";
GRANT SELECT ANY TABLE TO "PSPM";
--高级复制必须添加
GRANT SELECT ANY DICTIONARY TO "PSPM";
GRANT "CONNECT" TO "PSPM";
GRANT "DBA" TO "PSPM";
/
