ALTER TABLE PM_BSC_STAFF_INFO
MODIFY(VC_JOB NUMBER(20));


ALTER TABLE PM_BSC_STAFF_INFO
 ADD (VC_FORMATION_DATE  TIMESTAMP(6));

ALTER TABLE PM_BSC_STAFF_INFO
 ADD (VC_WORK_DATE  TIMESTAMP(6));


COMMENT ON COLUMN PM_BSC_STAFF_INFO.VC_EXTEND1 IS '现用于工作分工名称';
